### ISSUE TITLE
JSON Web Requests for Suggestions

### ISSUE THREAD

**Issue by Chopknee** [squirrelo/MovieNightBot#18]
Bot should have a "web API" for getting suggestions via a web request. The suggestions should be returned in a JSON format to be further processed.
There should be two separate requests. One that grabs data for Watched movies, and one for suggestions that have not been watched.

Data that should be in the requests;

Suggested Movies

{
	server_id: 1234563412421,
	suggested: [
		{
			imdb_id: ######,
			title: Title, 
			year: ####, 
			poster_url: URL,
 			full_size_poster_url: URL
 			total_score: ####
 			total_votes: ####
 			num_votes_entered: ####
 			date_suggested: DATE
 			suggestor: USERNAME
		},
	]
}

**Comment by squirrelo** [comment]
For servers that have the IMDB check off, this will return `null` for any IMDB-based info that is not available.
