### ISSUE TITLE
Add endpoint to get active vote data

### ISSUE THREAD

**Issue by Chopknee** [squirrelo/MovieNightBot#24]
Bot should return current vote info (if one is running) with a web API call. Data should be JSON. Exact format and naming can match database. 
For efficiency, there should be two separate calls. One call just grabs the latest vote numbers with movie titles, while the other call grabs vote numbers + all suggestion data related to the vote items (suggestion data + imdb data). Reduces bot workload and data tx when refreshing vote data.

**Comment by itsTheFae** [comment]
Is this part of the bot now with the new votes page?

**Comment by Chopknee** [comment]
This was resolved some time ago with the votes page. Fixed in commit cbf5209571301a10522a6b2aa165af8548ff5688.
