### ISSUE TITLE
Movie sorting needs to ignore common starting words like "The"

### ISSUE THREAD

**Issue by Chopknee** [squirrelo/MovieNightBot#32]
The bot should ignore common starting words like "A", "An", and "The" when sorting suggestions and watched titles.

**Comment by itsTheFae** [comment]
This should be possible in SQL.

**Comment by itsTheFae** [comment]
SQLite uses CASE statements in the ORDER BY clause to get this result.  Peewee supports these so it is certainly possible to make this happen.  
I can't test this right now but something like this in the `order_by()` should work out: 
```py
Case(None, (
    (Movie.movie_name.lower().startswith('a '), Movie.movie_name[2:]),
    (Movie.movie_name.lower().startswith('an '), Movie.movie_name[3:]),
    (Movie.movie_name.lower().startswith('the '), Movie.movie_name[4:])
    ), Movie.movie_name)
```

**Comment by itsTheFae** [comment]
@Chopknee  or  @squirrelo  would either of you mind testing PR #40 on the "live" data before merging this in?
