### ISSUE TITLE
Gracefully handle a deleted vote message

### ISSUE THREAD

**Issue by squirrelo** [squirrelo/MovieNightBot#36]
If someone somehow deletes the vote message before a vote is finished, handle this gracefully by ending/canceling the vote instead of erroring.

**Comment by Chopknee** [comment]
Seems to not be working at the moment.
I can delete the vote message and the bot won't end the old vote, or allow a new one to be created until after end_vote command is run.
Attached is the output log from the bot when a vote embed is deleted.
I might look in to this issue myself.
[log.txt](https://github.com/squirrelo/MovieNightBot/files/9173205/log.txt)
