### ISSUE TITLE
Bot fails to generate DB info when added to server offline

### ISSUE THREAD

**Issue by Chopknee** [squirrelo/MovieNightBot#55]
If the bot is invited to a server while offline, it does not generate the DB information required for that server. Any commands executed once the bot is online will generate a large number of errors. In order to get the bot working on that server, kicking and re-inviting the bot while it's online is required.
Generating server info is currently dependent on the server joined event. I think it would be a good idea to make the bot more robust by having any commands that require database access to first check if the database info has been generated (and generate it if nonexistent).

**Comment by squirrelo** [comment]
https://github.com/squirrelo/MovieNightBot/commit/1dbbda70ac4b423b112bfea5454617e11f7acc05
